apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    steps:
      - name: Check out source code
        uses: https://github.com/cloudbees-io/checkout@v2

      - name: Install dependencies and build
        uses: docker://node:20
        shell: sh
        run: |
          rm -rf node_modules package-lock.json
          npm install
          npm run build

      - name: Deploy to Netlify
        uses: docker://node:20
        shell: sh
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --dir=dist --site="$NETLIFY_SITE_ID" --auth="$NETLIFY_AUTH_TOKEN"
